-- AlterTable
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "show_on_qr" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "show_on_waiter" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "is_topping" BOOLEAN NOT NULL DEFAULT false;
